backup_full:
  name: 完整备份
  description: 创建带有可选排除项的完整备份。
  fields:
    name:
      name: 名称
      description: 备份名。可填。默认为当前日期和时间。
      example: "Automatic Backup {{ now().strftime('%Y-%m-%d') }}"
      selector:
        text:
    password:
      name: 密码
      description: 可填。用于保护备份的密码。
      example: "1234"
      selector:
        text:
    keep_days:
      name: 保留天数
      description: 可填。备份保留天数。
      example: "2"
      selector:
        number:
          min: 0
          max: 10000
          step: 0.01
          unit_of_measurement: 天
          mode: box
    exclude:
      name: 排除
      description: 可填。需要从备份里排除的Addons加载项/文件夹
      example: '{"addons": ["MariaDB"], "folders": ["Local add-ons", "share"]}'
      default: {"addons": ["MariaDB"], "folders": ["Local add-ons", "share"]}
      selector:
        object:
    download_path:
      name: 下载路径
      description: 可填。创建备份后下载到本地的路径。
      example: /usb_drive
      advanced: true
      selector:
        text:

backup_partial:
  name: 部分备份
  description: 创建部分备份。
  fields:
    name:
      name: 名称
      description: 备份名。可填。默认为当前日期和时间。
      example: "Automatic Backup {{ now().strftime('%Y-%m-%d') }}"
      selector:
        text:
    addons:
      name: Add-ons加载项
      description: 可填。要备份的加载项列表 (名字或者slug)。
      example: grafana, Configurator, core_mariadb
      selector:
        object:
    folders:
      name: 文件夹
      description: 可填。要备份的文件夹列表。
      example: homeassistant, Share, Local add-ons, ssl, media
      selector:
        object:
    password:
      name: 密码
      description: 可填。用于保护备份的密码。
      example: "1234"
      selector:
        text:
    keep_days:
      name: 保留天数
      description: 可填。备份保留天数。
      example: "2"
      selector:
        number:
          min: 0
          max: 10000
          step: 0.01
          unit_of_measurement: 天
          mode: box
    download_path:
      name: 下载路径
      description: 可填。创建备份后下载到本地的路径。
      example: /usb_drive
      advanced: true
      selector:
        text:

purge:
  name: 清除过期备份
  description: 清除过期备份。
